shop:
  outputs:
    dev:
      dataset: new_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/Bruno/Documents/Aulas Let's Code/analytics_engineering/analytics-382122-e8ed66060bc1.json
      location: US
      method: service-account
      priority: interactive
      project: analytics-382122
      threads: 1  
      type: bigquery
  target: dev
